# Generated by Django 3.0.3 on 2020-09-03 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('document', models.CharField(default='', max_length=25, verbose_name='Número documento')),
                ('letter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('m', 'M')], default='c', max_length=1, verbose_name='Letra')),
                ('center', models.PositiveIntegerField(verbose_name='Centro')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('image_login', models.ImageField(blank=True, max_length=150, null=True, upload_to='setting/company_image_login/%Y/%m/%d', verbose_name='Foto para Inicio de sesión')),
                ('image_sidebar', models.ImageField(blank=True, max_length=150, null=True, upload_to='setting/company_image_sidebar/%Y/%m/%d', verbose_name='Foto para Menú izquierdo')),
                ('image_favicon', models.ImageField(blank=True, max_length=150, null=True, upload_to='setting/company_image_favicon/%Y/%m/%d', verbose_name='Foto para pestaña de navegador')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
                ('image_ticket', models.ImageField(blank=True, max_length=150, null=True, upload_to='setting/company_image_ticket/%Y/%m/%d', verbose_name='Foto para Comprobante de venta')),
                ('document_IIBB', models.CharField(blank=True, default='', max_length=25, verbose_name='Número ingresos brutos')),
                ('date_activity_start', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de Inicio de actidad')),
                ('document_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Document_Type', verbose_name='Tipo documento')),
                ('fiscal_condition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Fiscal_Condition', verbose_name='Condición fiscal')),
                ('residence_city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.City', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
    ]
