# Generated by Django 3.0.3 on 2021-02-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0004_storages_and_help_texts'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.DocumentType', verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fiscal_condition',
            field=models.CharField(choices=[('IVA Responsable Inscripto', 'IVA Responsable Inscripto'), ('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Exento', 'IVA Exento'), ('No Responsable IVA', 'No Responsable IVA'), ('Responsable Monotributo', 'Responsable Monotributo')], default='Responsable Monotributo', max_length=60, verbose_name='Condición fiscal'),
        ),
    ]
