# Generated by Django 3.0.3 on 2021-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20210223_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_activity_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de actidad'),
        ),
    ]
