# Generated by Django 3.0.3 on 2021-03-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20210223_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='center',
        ),
        migrations.RemoveField(
            model_name='company',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number',
        ),
    ]
