# Generated by Django 3.0.3 on 2020-09-03 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('postcode', models.CharField(max_length=50, verbose_name='Código postal')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido')),
                ('business_name', models.CharField(default='', max_length=150, verbose_name='Nombre comercial')),
                ('trade_name', models.CharField(default='', max_length=150, verbose_name='Razón social')),
                ('comercial_address', models.CharField(default='', max_length=200, verbose_name='Dirección comercial')),
                ('document', models.CharField(default='', max_length=25, verbose_name='Número documento')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('sales_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Venta')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('date_birthday', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=6, verbose_name='Sexo')),
                ('photo', models.ImageField(blank=True, max_length=150, null=True, upload_to='sale/client_profile/%Y/%m/%d', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('photo', models.ImageField(max_length=150, upload_to='sale/client_profile/%Y/%m/%d', verbose_name='Imágen')),
                ('is_active', models.BooleanField(verbose_name='Foto actual')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Código fiscal')),
                ('fiscal_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre fiscal')),
                ('document', models.CharField(blank=True, max_length=25, verbose_name='Documento fiscal')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Codigo fiscal')),
                ('internal_code', models.CharField(blank=True, max_length=30, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fiscal_Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Codigo fiscal')),
                ('internal_code', models.CharField(blank=True, max_length=30, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Condición fiscal',
                'verbose_name_plural': 'Condiciones fiscales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale_Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('internal_code', models.CharField(blank=True, max_length=30, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Condición de venta',
                'verbose_name_plural': 'Condiciones de ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('m', 'M')], default='c', max_length=1, verbose_name='Letra')),
                ('center', models.PositiveIntegerField(verbose_name='Centro')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='SubTotal')),
                ('total_tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Total')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Client', verbose_name='Cliente')),
                ('sale_condition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Sale_Condition', verbose_name='Condición de Venta')),
                ('user_creation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Codigo fiscal')),
                ('internal_code', models.CharField(blank=True, max_length=30, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Tipo de comprobante',
                'verbose_name_plural': 'Tipos de comprobantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=1, verbose_name='Número de renglón')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Cantidad')),
                ('final_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio final')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='SubTotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Ticket')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalle de Boletas',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='voucher_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Voucher_Type', verbose_name='Tipo de comprobante'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Código fiscal')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Document_Type', verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Fiscal_Condition', verbose_name='Condición fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='residence_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.City', verbose_name='Ciudad de residencia'),
        ),
        migrations.AddField(
            model_name='client',
            name='sale_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Sale_Condition', verbose_name='Condición de Venta'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Client_Status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_creation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Province', verbose_name='Provincia'),
        ),
    ]
