# Generated by Django 3.0.3 on 2020-10-01 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
