# Generated by Django 3.0.3 on 2020-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20201001_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
