# Generated by Django 3.0.3 on 2021-02-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0004_storages_and_help_texts'),
        ('sale', '0003_auto_20201001_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id'], 'verbose_name': 'Comprobante de Venta', 'verbose_name_plural': 'Comprobantes de Ventas'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='receipt_afip',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.Receipt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.PointOfSales', verbose_name='Punto de Venta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='voucher_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.ReceiptType', verbose_name='Tipo de comprobante'),
        ),
    ]
