# Generated by Django 3.0.3 on 2021-02-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0004_storages_and_help_texts'),
        ('sale', '0004_auto_20210217_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_detail',
            options={'ordering': ['row_number'], 'verbose_name': 'Detalle de Comprobante de Venta', 'verbose_name_plural': 'Detalle de Comprobantes de Ventas'},
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.DocumentType', verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fiscal_condition',
            field=models.CharField(choices=[('IVA Responsable Inscripto', 'IVA Responsable Inscripto'), ('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Sujeto Exento', 'IVA Sujeto Exento'), ('Consumidor Final', 'Consumidor Final'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Proveedor del Exterior', 'Proveedor del Exterior'), ('Cliente del Exterior', 'Cliente del Exterior'), ('IVA Liberado - Ley Nº 19.640', 'IVA Liberado - Ley Nº 19.640'), ('IVA Responsable Inscripto - Agente de Percepción', 'IVA Responsable Inscripto - Agente de Percepción'), ('Monotributista Social', 'Monotributista Social'), ('IVA no alcanzado', 'IVA no alcanzado')], default='Consumidor Final', max_length=60, verbose_name='Condición fiscal'),
        ),
    ]
