# Generated by Django 3.0.3 on 2020-09-04 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('m', 'M')], default='c', max_length=1, verbose_name='Letra')),
                ('center', models.PositiveIntegerField(verbose_name='Centro')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='SubTotal')),
                ('total_tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Provider_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('photo', models.ImageField(max_length=150, upload_to='purchase/provider_profile/%Y/%m/%d', verbose_name='Imágen')),
                ('is_active', models.BooleanField(verbose_name='Foto actual')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase_Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('internal_code', models.CharField(blank=True, max_length=30, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Condición de compra',
                'verbose_name_plural': 'Condiciones de compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido')),
                ('business_name', models.CharField(default='', max_length=150, verbose_name='Nombre comercial')),
                ('trade_name', models.CharField(default='', max_length=150, verbose_name='Razón social')),
                ('comercial_address', models.CharField(default='', max_length=200, verbose_name='Dirección comercial')),
                ('document', models.CharField(default='', max_length=25, verbose_name='Número documento')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('purchase_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Compra')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono')),
                ('date_birthday', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, max_length=150, null=True, upload_to='purchase/provider_profile/%Y/%m/%d', verbose_name='Foto')),
                ('document_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Document_Type', verbose_name='Tipo documento')),
                ('fiscal_condition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Fiscal_Condition', verbose_name='Condición fiscal')),
                ('residence_city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.City', verbose_name='Ciudad de residencia')),
                ('sale_condition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase.Purchase_Condition', verbose_name='Condición de compra')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase.Provider_Status', verbose_name='Estado')),
                ('user_creation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=1, verbose_name='Número de renglón')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Cantidad')),
                ('final_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio final')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='SubTotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Product')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalle de Boletas',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase.Provider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase.Purchase_Condition', verbose_name='Condición de compra'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_creation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_user_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voucher_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sale.Voucher_Type', verbose_name='Tipo de comprobante'),
        ),
    ]
