# Generated by Django 3.0.3 on 2020-09-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='sale_condition',
            new_name='purchase_condition',
        ),
    ]
