# Generated by Django 3.0.3 on 2020-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200904_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
