# Generated by Django 3.0.3 on 2020-09-03 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=25)),
                ('image', models.ImageField(max_length=150, upload_to='stock/product/%Y/%m/%d', verbose_name='Imágen')),
                ('is_active', models.BooleanField(verbose_name='Imágen actual')),
            ],
            options={
                'verbose_name': 'Imágen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tax_IVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_code', models.PositiveIntegerField(verbose_name='Código fiscal')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('alicuot', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Alícuota')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Condición de IVA',
                'verbose_name_plural': 'Condiciones de IVA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit_Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fiscal_code', models.CharField(default='00', max_length=5, verbose_name='Código fiscal')),
                ('description', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('barcode', models.CharField(default='', max_length=150, verbose_name='Código de barra')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio de compra')),
                ('sale_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio de venta')),
                ('exception', models.BooleanField(default=False, verbose_name='Exento')),
                ('discount', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Descuento')),
                ('final_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio final')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to='stock/product/%Y/%m/%d', verbose_name='Imágen')),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stock')),
                ('date_expiration', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de vencimiento')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.Category', verbose_name='Categoría')),
                ('tax', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.Tax_IVA', verbose_name='Condición de IVA')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.Unit_Measure', verbose_name='Unidad de medida')),
                ('user_creation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
