# Generated by Django 3.0.3 on 2020-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_measure',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Abreviatura'),
        ),
    ]
