# Generated by Django 3.0.3 on 2021-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_unit_measure_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='stock/product/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
