# Generated by Django 3.0.3 on 2021-03-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0005_auto_20210223_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Total')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Saldo')),
                ('status', models.CharField(choices=[('earring', 'Pendiente'), ('compliment', 'Cumplido')], max_length=10, verbose_name='Situación')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReceiptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Importe afectación')),
                ('ticket_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCurrentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Saldo')),
                ('status', models.CharField(choices=[('paid', 'Pagado'), ('owed', 'Adeudado')], max_length=10, verbose_name='Situación')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Ticket', verbose_name='Comprobante')),
            ],
        ),
    ]
