# Generated by Django 3.0.3 on 2021-03-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210223_0856'),
        ('client_current_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReceiptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Importe afectación')),
            ],
        ),
        migrations.RenameModel(
            old_name='TicketCurrentAccount',
            new_name='ClientCurrentAccount',
        ),
        migrations.RenameModel(
            old_name='TicketReceipt',
            new_name='ClientReceipt',
        ),
        migrations.DeleteModel(
            name='TicketReceiptDetail',
        ),
        migrations.AddField(
            model_name='clientreceiptdetail',
            name='client_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_current_account.ClientReceipt'),
        ),
        migrations.AddField(
            model_name='clientreceiptdetail',
            name='ticket_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Ticket'),
        ),
    ]
