# Generated by Django 3.0.3 on 2021-03-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_current_account', '0002_auto_20210303_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcurrentaccount',
            options={'ordering': ['id'], 'verbose_name': 'Cuenta Corriente de Cliente', 'verbose_name_plural': 'Cuenta Corriente de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientreceipt',
            options={'ordering': ['id'], 'verbose_name': 'Recibo de Cliente', 'verbose_name_plural': 'Recibos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientreceiptdetail',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Recibo de Cliente', 'verbose_name_plural': 'Detalle de Recibos de Clientes'},
        ),
    ]
