# Generated by Django 3.0.3 on 2021-03-11 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210223_0856'),
        ('client_current_account', '0003_auto_20210303_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreceipt',
            name='center',
            field=models.PositiveIntegerField(default=1, verbose_name='Punto de Cobro'),
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sale.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='letter',
            field=models.CharField(default='X', max_length=1, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
