# Generated by Django 3.0.3 on 2021-03-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_current_account', '0004_auto_20210311_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreceiptdetail',
            name='ticket_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_current_account.ClientCurrentAccount'),
        ),
    ]
