# Generated by Django 3.0.3 on 2021-03-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210223_0856'),
        ('client_current_account', '0005_auto_20210312_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreceipt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clientreceiptdetail',
            name='client_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_current_account.ClientReceipt', verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='clientreceiptdetail',
            name='ticket_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_current_account.ClientCurrentAccount', verbose_name='Comprobante'),
        ),
    ]
